### ISSUE TITLE
Unexpected panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by twlz0ne** [saibing/bingo#101]
### Behaviour

"unexpected panic: runtime error: invalid memory address or nil pointer dereference"

### Steps to reproduce

- Open main.go
- Move cursor to next line

### Environment

- macOS 10.11.6
- Emacs 27.0.50
- bingo (7ba4d36) 2019-02-16

### Error callstack

```log
langserver-go: reading on stdin, writing on stdout
--> request #99: initialize: {"processId":48000,"rootPath":"/Users/***/scratch/electron/gotron-demo/","rootUri":"file:///Users/***/scratch/electron/gotron-demo/","capabilities":{"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"]},"applyEdit":true,"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"declaration":{"linkSupport":true},"definition":{"linkSupport":true},"implementation":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"synchronization":{"willSave":true,"didSave":true,"willSaveWaitUntil":true},"documentSymbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true}},"signatureHelp":{"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}}}},"initializationOptions":{"funcSnippetEnabled":true,"gocodeCompletionEnabled":true,"formatTool":"goimports","goimportsLocalPrefix":"","maxParallelism":null,"useBinaryPkgCache":true,"diagnosticsEnabled":true}}
Passing an initialize rootPath URI ("file:///Users/***/scratch/electron/gotron-demo/") is deprecated. Use rootUri instead.
<-- notif: window/logMessage: {"type":3,"message":"GOPATH: [/Users/***/go], import path: "}
<-- notif: window/logMessage: {"type":3,"message":"GO111MODULE=auto, module mode"}
<-- notif: window/showMessage: {"type":3,"message":"load /Users/***/scratch/electron/gotron-demo/ successfully! elapsed time: 2 seconds, cache: false, go module: false."}
<-- result #99: initialize: {"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"implementationProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true,"xworkspaceReferencesProvider":true,"xdefinitionProvider":true,"xworkspaceSymbolByProperties":true}}
--> notif: initialized: {}
--> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///Users/***/scratch/electron/gotron-demo/main.go","languageId":"go","version":0,"text":"package main\n\nimport (\n\t\"github.com/Equanox/gotron\"\n)\n\nfunc main() {\n\t// Create a new browser window instance\n\twindow, err := gotron.New()\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\n\t// After default window size and window title.\n\twindow.WindowOptions.Width = 1200\n\twindow.WindowOptions.Height = 980\n\twindow.WindowOptions.Title = \"Gotron\"\n\twindow.\n\n\t// Start the browser window.\n\t// This will establish a golang \u003c=\u003e nodejs bridge using websockets,\n\t// to control ElectronBrowserWindow with our window object.\n\tdone, err := window.Start()\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\n\t// Open dev tools must be used after window.Start\n\t// window.OpenDevTools(\n\n\t// Wait for the application to close\n\t\u003c-done\n}\n"}}
--> request #100: textDocument/hover: {"textDocument":{"uri":"file:///Users/***/scratch/electron/gotron-demo/main.go"},"position":{"line":1,"character":0}}
--> request #101: textDocument/signatureHelp: {"textDocument":{"uri":"file:///Users/***/scratch/electron/gotron-demo/main.go"},"position":{"line":1,"character":0}}
<-- error #100: textDocument/hover: {"code":0,"message":"package is null for file file:///Users/***/scratch/electron/gotron-demo/main.go","data":null}
panic serving textDocument/signatureHelp: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
github.com/saibing/bingo/langserver/internal/util.Panicf(0x451e6a0, 0x49e7e00, 0x45aedec, 0x2, 0xc00028b870, 0x1, 0x1, 0xc00028b880, 0x405bed6)
	/Users/***/tools/develop/bingo/langserver/internal/util/util.go:116 +0x93
github.com/saibing/bingo/langserver.(*LangHandler).Handle.func1(0xc0002b03c0, 0xc00028be60)
	/Users/***/tools/develop/bingo/langserver/handler.go:107 +0xc4
panic(0x451e6a0, 0x49e7e00)
	/Users/***/.goenv/versions/1.11.5/src/runtime/panic.go:513 +0x1b9
go/token.(*File).Size(...)
	/Users/***/.goenv/versions/1.11.5/src/go/token/position.go:120
github.com/saibing/bingo/langserver.lineStart(0x0, 0x2, 0xc00014a270)
	/Users/***/tools/develop/bingo/langserver/position.go:76 +0x37
github.com/saibing/bingo/langserver.fromProtocolPosition(0x0, 0x1, 0x0, 0xc0002be100)
	/Users/***/tools/develop/bingo/langserver/position.go:49 +0x38
github.com/saibing/bingo/langserver.(*LangHandler).handleTextDocumentSignatureHelp(0xc0001ec0c0, 0x4667220, 0xc00001e0c0, 0x4665620, 0xc0001e2100, 0xc0002b03c0, 0xc0002be080, 0x36, 0x1, 0x0, ...)
	/Users/***/tools/develop/bingo/langserver/signature.go:28 +0x104
github.com/saibing/bingo/langserver.(*LangHandler).Handle(0xc0001ec0c0, 0x4667220, 0xc00001e0c0, 0x4665620, 0xc0001e2100, 0xc0002b03c0, 0x0, 0x0, 0x0, 0x0)
	/Users/***/tools/develop/bingo/langserver/handler.go:304 +0x28d7
github.com/saibing/bingo/langserver.(*LangHandler).handle(0xc0001ec0c0, 0x4667260, 0xc0000b0008, 0xc0001e2100, 0xc0002b03c0, 0x4015605, 0xc00000c2f0, 0xc00004efb0, 0x10)
	/Users/***/tools/develop/bingo/langserver/handler.go:97 +0x66
github.com/saibing/bingo/langserver.(*LangHandler).handle-fm(0x4667260, 0xc0000b0008, 0xc0001e2100, 0xc0002b03c0, 0xc00004efb0, 0x0, 0xc00004ef30, 0x0)
	/Users/***/tools/develop/bingo/langserver/handler.go:24 +0x52
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc0000621a0, 0x4667260, 0xc0000b0008, 0xc0001e2100, 0xc0002b03c0)
	/Users/***/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20180831160525-549eb959f029/handler_with_error.go:21 +0x73
created by github.com/saibing/bingo/langserver.lspHandler.Handle
	/Users/***/tools/develop/bingo/langserver/handler.go:48 +0xfb
<-- error #101: textDocument/signatureHelp: {"code":0,"message":"unexpected panic: runtime error: invalid memory address or nil pointer dereference","data":null}
```

**Comment by saibing** [comment]
@twlz0ne 

Please try the latest version bingo

**Comment by twlz0ne** [comment]
Updated to 9349bc0 (2019-02-19), still no luck.

**Comment by czarnecki** [comment]
I had the same problem and solved it by putting my project into `$GOPATH/src/projectname`.

**Comment by twlz0ne** [comment]
> putting my project into `$GOPATH/src/projectname`

Thanks. Symlink works too.

**Comment by JayceCao** [comment]
The problem still exists on the latest version. OS is Arch Linux.

**Comment by czarnecki** [comment]
> The problem still exists on the latest version. OS is Arch Linux.

Alternatively using the new module system should work.
See: https://github.com/golang/go/wiki/Modules#quick-start
